[profile.default]
src = "nft"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
